### ISSUE TITLE
Change image size

### ISSUE THREAD

**Issue by developius** [kalinr/kalins-pdf-creation-station#4]
I would like to be able to scale the images in my posts. I've had a poke in the PHP files and not found anything pointing to the image sizes? I found your comment in https://github.com/kalinr/kalins-pdf-creation-station/blob/f310513c80345e6a37c472444a08efe845333586/kalins-pdf-creation-station.php#L1037-L1038 but that's only about the post featured image? I'd really appreciate some pointers as to where this gets handled!

**Comment by kalinr** [comment]
In the post_thumb shortcode there is the size parameter that you can add. Unfortunately with that, wordpress limits you to "thumbnail", "medium", "large", and "full". However, you can always add the width and height attributes to the img tag to scale the image.

**Comment by developius** [comment]
Ah, great! I'll just add the sizes to the image tags :)
